### ISSUE TITLE
h7 Client.py issue

### ISSUE THREAD

**Issue by ghost** [sv24alpha/SDN-oriented-DDoS-blocking-scheme#1]
Hi, After following your step by step guide, where I am currently stuck, where when i execute 'python client.py' in h7 i have the prompted error below (attached image) can you please assist me of how i can amend this error?

Much thanks!
![virtualbox_flood4ba1_28_09_2017_18_29_18](https://user-images.githubusercontent.com/20652151/30996638-9d4198b8-a505-11e7-93ca-82629b4c8b29.png)

**Comment by sv24alpha** [comment]
Hey, you might need to look at the IP assignment, because "no route to host" means it is not in the same network.
